#!/usr/bin/env bash
# multi tasker script
echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap ' echo "I hate the kill command"' SIGTERM
	trap ' echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid;  exit' SIGQUIT SIGTERM
done


