#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
#   display hours from 0 to 12
#   display minutes from 1 to 59

hr=0
min=1

while [ $hr -le 12 ]; do
	echo "Hour: $hr"
	while [ $min -le 59 ]; do
		echo $min
		min=$((min+1))
	done
	min=$((1))
	hr=$((hr+1))
done
