#!/usr/bin/env bash
# info about School file
if [ -e "School" ]; then
	echo "school file exists"
	if [ -z "School" ]; then
	  echo "School file is empty"
	else
	  echo "School file is not empty"
	fi

	if [ -f "School" ]; then
	  echo "School is a regular file"
	fi

else
  echo "school file does not exist"
fi
